
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE_ID = 'FETCH_MOVIE_ID';
export const LOADING = 'LOADING';

export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE";